version: '3.8'

services:
  nginx-reverse-proxy:
    image: nginx:1.25
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd 
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - node-app-dev
      - node-app-prod 
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  node-app-dev:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: node-app-dev
    restart: unless-stopped
    environment:
      - APP_BG_COLOR=green
    expose:
      - 3000
  
  node-app-prod:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: node-app-prod
    restart: unless-stopped
    environment:
      - APP_BG_COLOR=purple
    expose:
      - 3000

