version: "3.8"

services:
  node-app-dev:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: node-app-dev
    restart: unless-stopped
    environment:
      - APP_BG_COLOR=green
    expose:
      - 3000
    networks:
      - nginx_net
